create database mysqlproject1;
use mysqlproject1;
show tables;
select* from ss_store

#-----Sales Performance Analysis-----------

#1.What is the overall revenue generated by the business?
select format(sum(sales),2) as 'Total Revenue' 
from ss_store;

#2.Which are the top 10 highest revenue-generating products?
select sub_category,format(sum(sales),2) as ' Total Revenue' 
from ss_store
group by sub_category
order by sum(sales) desc 
limit 10;
 
#3.Which products contribute the least to total sales?
select sub_category,format(sum(sales),2) as ' Total Revenue' 
from ss_store 
group by sub_category 
order by sum(sales) 
limit 5;

#4.What percentage of total revenue comes from each category?
select category,
	format(sum(sales),2) as ' Total Revenue' 
from ss_store 
group by category;

#5.Which category contributes the most revenue to the business?
select category,
        format(sum(sales),2) as ' Total Revenue' 
from ss_store 
group by category 
order by category desc 
limit 1;


#-----Profitability Analysis------

#6.Which category generates the highest profit?
select category,
      format(sum(profit),2) as ' Total Profit'
from ss_store
group by category 
order by category desc 
limit 1;

#7.Which sub-categories are operating at a loss?
select sub_category,
       format(sum(profit),2) as ' Total Loss'
from ss_store 
group by sub_category 
having sum(profit)<0
order by sum(profit) desc;

#8.What are the top 10 most profitable products?
select sub_category,
       format(sum(profit),2) as ' Total Profit' 
from ss_store 
group by sub_category 
having sum(profit) >0 
order by sum(profit) desc 
limit 10;

#9.What are the top 10 loss-making products?
select sub_category,
       format(sum(profit),2) as ' Total Loss' 
from ss_store 
group by sub_category 
having sum(profit) <0 
order by sum(profit) desc 
limit 10;

#10.Which states contribute the highest profit?
select state,
       format(sum(profit),2) as ' Total Profit' 
from ss_store 
group by state 
order by sum(profit) desc 
limit 10;

#----Regional Analysis-----
#11.Which region generates the highest sales revenue?
select region,
	   format(sum(sales),2) as ' Total Revenue' 
from ss_store 
group by region 
order by region desc 
limit 1;

#12.Which region generates the highest profit?
select region,
       format(sum(profit),2) as ' Total Profit' 
from ss_store 
group by region 
order by region  
limit 1;

#13.Which states are consistently generating losses?
select state,
	format(sum(profit),2) as ' Total Loss' 
from ss_store 
group by state 
having sum(profit) <0 
order by sum(profit) desc;

#14.Which regions have profit lower than the company average?
SELECT Region,
       format(SUM(Profit),2) AS Total_Profit
FROM ss_store
GROUP BY Region
HAVING SUM(Profit) <
(
SELECT AVG(region_profit)
FROM
(
SELECT SUM(Profit) AS region_profit
FROM ss_store
GROUP BY Region
) AS x
);

#15.What is the sales and profit contribution of each region?
select region,
	   format(sum(profit),2) as ' Total Profit',
	   format(sum(sales),2) as 'Total Sales' 
from ss_store 
group by region;

#----Customer Segment Analysis--------

#16.Which customer segment generates the highest revenue?
select segment,
       format(sum(sales),2) as 'profit' 
from ss_store 
group by segment 
order by sum(sales) desc; 

#17.Which customer segment generates the highest profit?
select segment,
       format(sum(profit),2) as 'profit' 
from ss_store 
group by segment 
order by sum(profit) desc;

#18.Which segment receives the highest average discount?
select segment,
       format(avg(discount),5) Avg_Discount from ss_store 
group by segment 
order by avg(discount) desc 
limit 1;

#19.What is the profit margin for each customer segment?
select segment,
       format(sum(profit)/sum(sales)*100,5) as profit_margin 
from ss_store 
group by segment;

#20.Which segment has the lowest profitability despite high sales?
select segment,
       format(sum(profit),2) as ' Total Profit',
       format(sum(sales),2) as 'Total Sales',
       format(sum(profit)/sum(sales)*100,5) as 'Profit Margin'
from ss_store 
group by segment  
order by sum(profit)/sum(sales)*100 desc;

#-----Discount Analysis-------

#21.How does discounting impact profitability across categories?
SELECT Category,
       format(AVG(Discount),5) AS 'Avg_Discount',
       format(SUM(Profit),2) AS 'Profit'
FROM ss_store
GROUP BY Category;

#22.Which products receive the highest average discount?
SELECT sub_category,
       format(AVG(Discount),5) AS Avg_Discount
FROM ss_store
GROUP BY sub_category
ORDER BY Avg_Discount DESC
LIMIT 10;

#23.Which categories suffer losses due to excessive discounts?
SELECT Category,
       format(AVG(Discount),5) AS Avg_Discount,
       format(SUM(Profit),2) AS Profit
FROM ss_store
GROUP BY Category
HAVING SUM(Profit) < 0;

#-----Business Growth Insights---

#24.Identify categories whose sales are above the overall average category sales.
SELECT Category,
       format(SUM(Sales),5) AS Total_Sales
FROM ss_store
GROUP BY Category
HAVING SUM(Sales) >
(
SELECT AVG(category_sales)
FROM
(
SELECT SUM(Sales) AS category_sales
FROM ss_store
GROUP BY Category
) AS x
);

#25.Identify states whose profits are above the overall average state profit.
SELECT State,
       format(SUM(Profit),2) AS Total_Profit
FROM ss_store
GROUP BY State
HAVING SUM(Profit) >
(
SELECT AVG(state_profit)
FROM
(
SELECT SUM(Profit) AS state_profit
FROM ss_store
GROUP BY State
) AS x
);
